import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "./context/useContext";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Muhammadi Medical Trust",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AppProvider>
          {children}
          <Toaster />
        </AppProvider>
      </body>
    </html>
  );
}
